using CoinBot.Domain.Enums;

namespace CoinBot.Application.Abstractions.Ai;

public interface IAiShadowDecisionService
{
    Task<AiShadowDecisionSnapshot> CaptureAsync(
        AiShadowDecisionWriteRequest request,
        CancellationToken cancellationToken = default);

    Task<AiShadowDecisionSnapshot?> GetLatestAsync(
        string userId,
        Guid botId,
        string symbol,
        string timeframe,
        CancellationToken cancellationToken = default);

    Task<IReadOnlyCollection<AiShadowDecisionSnapshot>> ListRecentAsync(
        string userId,
        Guid botId,
        string symbol,
        string timeframe,
        int take = 20,
        CancellationToken cancellationToken = default);

    Task<AiShadowDecisionSummarySnapshot> GetSummaryAsync(
        string userId,
        Guid botId,
        string symbol,
        string timeframe,
        int take = 200,
        CancellationToken cancellationToken = default);
}

public sealed record AiShadowDecisionWriteRequest(
    Guid Id,
    string UserId,
    Guid BotId,
    Guid? ExchangeAccountId,
    Guid? TradingStrategyId,
    Guid? TradingStrategyVersionId,
    Guid? StrategySignalId,
    Guid? StrategySignalVetoId,
    Guid? FeatureSnapshotId,
    Guid? StrategyDecisionTraceId,
    Guid? HypotheticalDecisionTraceId,
    string CorrelationId,
    string StrategyKey,
    string Symbol,
    string Timeframe,
    DateTime EvaluatedAtUtc,
    DateTime? MarketDataTimestampUtc,
    string? FeatureVersion,
    string StrategyDirection,
    int? StrategyConfidenceScore,
    string? StrategyDecisionOutcome,
    string? StrategyDecisionCode,
    string? StrategySummary,
    string AiDirection,
    decimal AiConfidence,
    string AiReasonSummary,
    string AiProviderName,
    string? AiProviderModel,
    int AiLatencyMs,
    bool AiIsFallback,
    string? AiFallbackReason,
    bool RiskVetoPresent,
    string? RiskVetoReason,
    string? RiskVetoSummary,
    bool PilotSafetyBlocked,
    string? PilotSafetyReason,
    string? PilotSafetySummary,
    ExecutionEnvironment TradingMode,
    ExchangeDataPlane Plane,
    string FinalAction,
    bool HypotheticalSubmitAllowed,
    string? HypotheticalBlockReason,
    string? HypotheticalBlockSummary,
    string NoSubmitReason,
    string? FeatureSummary,
    string AgreementState);

public sealed record AiShadowDecisionSnapshot(
    Guid Id,
    string UserId,
    Guid BotId,
    Guid? ExchangeAccountId,
    Guid? TradingStrategyId,
    Guid? TradingStrategyVersionId,
    Guid? StrategySignalId,
    Guid? StrategySignalVetoId,
    Guid? FeatureSnapshotId,
    Guid? StrategyDecisionTraceId,
    Guid? HypotheticalDecisionTraceId,
    string CorrelationId,
    string StrategyKey,
    string Symbol,
    string Timeframe,
    DateTime EvaluatedAtUtc,
    DateTime? MarketDataTimestampUtc,
    string? FeatureVersion,
    string StrategyDirection,
    int? StrategyConfidenceScore,
    string? StrategyDecisionOutcome,
    string? StrategyDecisionCode,
    string? StrategySummary,
    string AiDirection,
    decimal AiConfidence,
    string AiReasonSummary,
    string AiProviderName,
    string? AiProviderModel,
    int AiLatencyMs,
    bool AiIsFallback,
    string? AiFallbackReason,
    bool RiskVetoPresent,
    string? RiskVetoReason,
    string? RiskVetoSummary,
    bool PilotSafetyBlocked,
    string? PilotSafetyReason,
    string? PilotSafetySummary,
    ExecutionEnvironment TradingMode,
    ExchangeDataPlane Plane,
    string FinalAction,
    bool HypotheticalSubmitAllowed,
    string? HypotheticalBlockReason,
    string? HypotheticalBlockSummary,
    string NoSubmitReason,
    string? FeatureSummary,
    string AgreementState,
    DateTime CreatedAtUtc);

public sealed record AiShadowDecisionSummarySnapshot(
    string UserId,
    Guid BotId,
    string Symbol,
    string Timeframe,
    int TotalCount,
    int ShadowOnlyCount,
    int NoSubmitCount,
    int LongCount,
    int ShortCount,
    int NeutralCount,
    int FallbackCount,
    int RiskVetoCount,
    int PilotSafetyBlockCount,
    int AgreementCount,
    int DisagreementCount,
    int NotApplicableCount,
    decimal AverageAiConfidence,
    int HighConfidenceCount,
    int MediumConfidenceCount,
    int LowConfidenceCount,
    IReadOnlyCollection<AiShadowMetricBucketSnapshot> NoSubmitReasons,
    IReadOnlyCollection<AiShadowMetricBucketSnapshot> HypotheticalBlockReasons);

public sealed record AiShadowMetricBucketSnapshot(string Key, int Count);
