// <auto-generated />
using CoinBot.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CoinBot.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260401170000_AddTradingBotExecutionPilotFields")]
    partial class AddTradingBotExecutionPilotFields
    {
    }
}
