using CoinBot.Domain.Enums;

namespace CoinBot.Application.Abstractions.Risk;

public sealed record PreTradeRiskSnapshot(
    bool IsVirtualCheck,
    Guid? RiskProfileId,
    string? RiskProfileName,
    bool KillSwitchEnabled,
    decimal CurrentEquity,
    decimal CurrentGrossExposure,
    decimal CurrentLeverage,
    decimal CurrentExposurePercentage,
    decimal CurrentDailyLossAmount,
    decimal CurrentDailyLossPercentage,
    decimal? MaxDailyLossPercentage,
    decimal? MaxExposurePercentage,
    decimal? MaxLeverage,
    int OpenPositionCount,
    DateTime EvaluatedAtUtc,
    string? OwnerUserId = null,
    Guid? BotId = null,
    string? Symbol = null,
    string? BaseAsset = null,
    string? Timeframe = null,
    ExecutionOrderSide? Side = null,
    decimal? RequestedQuantity = null,
    decimal? RequestedPrice = null,
    decimal RequestedNotional = 0m,
    decimal CurrentWeeklyLossAmount = 0m,
    decimal CurrentWeeklyLossPercentage = 0m,
    decimal? MaxWeeklyLossPercentage = null,
    decimal ProjectedGrossExposure = 0m,
    decimal ProjectedLeverage = 0m,
    decimal ProjectedExposurePercentage = 0m,
    decimal CurrentSymbolExposureAmount = 0m,
    decimal ProjectedSymbolExposureAmount = 0m,
    decimal CurrentSymbolExposurePercentage = 0m,
    decimal ProjectedSymbolExposurePercentage = 0m,
    decimal? MaxSymbolExposurePercentage = null,
    int ProjectedOpenPositionCount = 0,
    int? MaxConcurrentPositions = null,
    decimal CurrentCoinExposureAmount = 0m,
    decimal ProjectedCoinExposureAmount = 0m,
    decimal CurrentCoinExposurePercentage = 0m,
    decimal ProjectedCoinExposurePercentage = 0m,
    decimal? MaxCoinExposurePercentage = null);
