namespace CoinBot.Application.Abstractions.Monitoring;

public sealed record MarketScannerDashboardSnapshot(
    Guid? ScanCycleId,
    DateTime? LastScanCompletedAtUtc,
    int ScannedSymbolCount,
    int EligibleCandidateCount,
    int TopCandidateCount,
    string UniverseSource,
    string? BestCandidateSymbol,
    decimal? BestCandidateScore,
    string? BestCandidateRankingSummary,
    IReadOnlyCollection<MarketScannerCandidateSnapshot> TopCandidates,
    IReadOnlyCollection<MarketScannerCandidateSnapshot> RejectedSamples,
    MarketScannerHandoffSnapshot LatestHandoff,
    MarketScannerHandoffSnapshot LastSuccessfulHandoff,
    MarketScannerHandoffSnapshot LastBlockedHandoff,
    string? CycleSummary = null,
    string? RejectionSummary = null,
    string? DirectionalConflictSummary = null,
    string? SameDirectionSummary = null,
    string? DuplicateSummary = null,
    string? GuardrailSummary = null,
    int AiRankingFallbackCount = 0,
    int AiRankingSuppressionCount = 0,
    int AiRankingTopCandidateChangedCount = 0,
    string? AiRankingStatusTitle = null,
    string? AiRankingStatusSummary = null,
    string? AiRankingStatusReason = null)
{
    public static MarketScannerDashboardSnapshot Empty()
    {
        return new MarketScannerDashboardSnapshot(
            ScanCycleId: null,
            LastScanCompletedAtUtc: null,
            ScannedSymbolCount: 0,
            EligibleCandidateCount: 0,
            TopCandidateCount: 0,
            UniverseSource: "n/a",
            BestCandidateSymbol: null,
            BestCandidateScore: null,
            BestCandidateRankingSummary: null,
            TopCandidates: Array.Empty<MarketScannerCandidateSnapshot>(),
            RejectedSamples: Array.Empty<MarketScannerCandidateSnapshot>(),
            LatestHandoff: MarketScannerHandoffSnapshot.Empty(),
            LastSuccessfulHandoff: MarketScannerHandoffSnapshot.Empty(),
            LastBlockedHandoff: MarketScannerHandoffSnapshot.Empty(),
            CycleSummary: null,
            RejectionSummary: null,
            DirectionalConflictSummary: null,
            SameDirectionSummary: null,
            DuplicateSummary: null,
            GuardrailSummary: null,
            AiRankingFallbackCount: 0,
            AiRankingSuppressionCount: 0,
            AiRankingTopCandidateChangedCount: 0,
            AiRankingStatusTitle: null,
            AiRankingStatusSummary: null,
            AiRankingStatusReason: null);
    }
}
