using CoinBot.Domain.Enums;

namespace CoinBot.Application.Abstractions.Monitoring;

public sealed record MarketScannerHandoffSnapshot(
    Guid? HandoffAttemptId,
    Guid? ScanCycleId,
    Guid? SelectedCandidateId,
    string? SelectedSymbol,
    string? SelectedTimeframe,
    DateTime? SelectedAtUtc,
    int? CandidateRank,
    decimal? CandidateMarketScore,
    decimal? CandidateScore,
    string SelectionReason,
    string? OwnerUserId,
    Guid? BotId,
    string? StrategyKey,
    Guid? TradingStrategyId,
    Guid? TradingStrategyVersionId,
    Guid? StrategySignalId,
    Guid? StrategySignalVetoId,
    string StrategyDecisionOutcome,
    string? StrategyVetoReasonCode,
    int? StrategyScore,
    string? RiskOutcome,
    string? RiskVetoReasonCode,
    string? RiskSummary,
    decimal? RiskCurrentDailyLossPercentage,
    decimal? RiskMaxDailyLossPercentage,
    decimal? RiskCurrentWeeklyLossPercentage,
    decimal? RiskMaxWeeklyLossPercentage,
    decimal? RiskCurrentLeverage,
    decimal? RiskProjectedLeverage,
    decimal? RiskMaxLeverage,
    decimal? RiskCurrentSymbolExposurePercentage,
    decimal? RiskProjectedSymbolExposurePercentage,
    decimal? RiskMaxSymbolExposurePercentage,
    int? RiskCurrentOpenPositions,
    int? RiskProjectedOpenPositions,
    int? RiskMaxConcurrentPositions,
    string? RiskBaseAsset,
    decimal? RiskCurrentCoinExposurePercentage,
    decimal? RiskProjectedCoinExposurePercentage,
    decimal? RiskMaxCoinExposurePercentage,
    string ExecutionRequestStatus,
    ExecutionOrderSide? ExecutionSide,
    ExecutionOrderType? ExecutionOrderType,
    ExecutionEnvironment? ExecutionEnvironment,
    decimal? ExecutionQuantity,
    decimal? ExecutionPrice,
    string? BlockerCode,
    string? BlockerDetail,
    string? BlockerSummary,
    string? GuardSummary,
    string? CorrelationId,
    DateTime? CompletedAtUtc,
    string DecisionOutcome = "Unknown",
    DateTime? DecisionAtUtc = null,
    string? DecisionReasonType = null,
    string? DecisionReasonCode = null,
    string? DecisionSummary = null,
    DateTime? MarketDataLastCandleAtUtc = null,
    int? MarketDataAgeMilliseconds = null,
    int? MarketDataStaleThresholdMilliseconds = null,
    string? MarketDataStaleReason = null,
    string? ContinuityState = null,
    int? ContinuityGapCount = null,
    DateTime? ContinuityGapStartedAtUtc = null,
    DateTime? ContinuityGapLastSeenAtUtc = null,
    DateTime? ContinuityRecoveredAtUtc = null)
{
    public static MarketScannerHandoffSnapshot Empty()
    {
        return new MarketScannerHandoffSnapshot(
            HandoffAttemptId: null,
            ScanCycleId: null,
            SelectedCandidateId: null,
            SelectedSymbol: null,
            SelectedTimeframe: null,
            SelectedAtUtc: null,
            CandidateRank: null,
            CandidateMarketScore: null,
            CandidateScore: null,
            SelectionReason: "NoHandoffAttempt",
            OwnerUserId: null,
            BotId: null,
            StrategyKey: null,
            TradingStrategyId: null,
            TradingStrategyVersionId: null,
            StrategySignalId: null,
            StrategySignalVetoId: null,
            StrategyDecisionOutcome: "NotEvaluated",
            StrategyVetoReasonCode: null,
            StrategyScore: null,
            RiskOutcome: null,
            RiskVetoReasonCode: null,
            RiskSummary: null,
            RiskCurrentDailyLossPercentage: null,
            RiskMaxDailyLossPercentage: null,
            RiskCurrentWeeklyLossPercentage: null,
            RiskMaxWeeklyLossPercentage: null,
            RiskCurrentLeverage: null,
            RiskProjectedLeverage: null,
            RiskMaxLeverage: null,
            RiskCurrentSymbolExposurePercentage: null,
            RiskProjectedSymbolExposurePercentage: null,
            RiskMaxSymbolExposurePercentage: null,
            RiskCurrentOpenPositions: null,
            RiskProjectedOpenPositions: null,
            RiskMaxConcurrentPositions: null,
            RiskBaseAsset: null,
            RiskCurrentCoinExposurePercentage: null,
            RiskProjectedCoinExposurePercentage: null,
            RiskMaxCoinExposurePercentage: null,
            ExecutionRequestStatus: "NotCreated",
            ExecutionSide: null,
            ExecutionOrderType: null,
            ExecutionEnvironment: null,
            ExecutionQuantity: null,
            ExecutionPrice: null,
            BlockerCode: null,
            BlockerDetail: null,
            BlockerSummary: null,
            GuardSummary: null,
            CorrelationId: null,
            CompletedAtUtc: null,
            DecisionOutcome: "Unknown",
            DecisionAtUtc: null,
            DecisionReasonType: null,
            DecisionReasonCode: null,
            DecisionSummary: null,
            MarketDataLastCandleAtUtc: null,
            MarketDataAgeMilliseconds: null,
            MarketDataStaleThresholdMilliseconds: null,
            MarketDataStaleReason: null,
            ContinuityState: null,
            ContinuityGapCount: null,
            ContinuityGapStartedAtUtc: null,
            ContinuityGapLastSeenAtUtc: null,
            ContinuityRecoveredAtUtc: null);
    }
}
