namespace CoinBot.Application.Abstractions.Monitoring;

public sealed record MarketScannerCandidateSnapshot(
    string Symbol,
    string UniverseSource,
    DateTime ObservedAtUtc,
    DateTime? LastCandleAtUtc,
    decimal? LastPrice,
    decimal? QuoteVolume24h,
    decimal MarketScore,
    int? StrategyScore,
    string? ScoringSummary,
    IReadOnlyCollection<string> AdvisoryLabels,
    IReadOnlyCollection<string> AdvisoryReasonCodes,
    string? AdvisorySummary,
    int? AdvisoryShadowScore,
    IReadOnlyCollection<string> AdvisoryShadowContributions,
    bool IsEligible,
    string? RejectionReason,
    decimal Score,
    int? Rank,
    bool IsTopCandidate,
    decimal? CandidateScore = null,
    decimal? RiskPenalty = null,
    decimal? VolatilityScore = null,
    decimal? LiquidityScore = null,
    string? TrendAlignment = null,
    string? DirectionalConflictStatus = null,
    string? RankingDecision = null,
    string? RankingReasonCode = null,
    string? RankingSummary = null,
    string? AiRankingMode = null,
    decimal? AiRankingClassicalScore = null,
    decimal? AiRankingCombinedScore = null,
    decimal? AiRankingInfluenceWeight = null,
    decimal? AiRankingOutcomeCoveragePercent = null,
    string? AiRankingFallbackReason = null,
    string? AiRankingAdaptiveFilterState = null,
    string? AiRankingAdaptiveFilterReason = null);
