namespace CoinBot.Application.Abstractions.Administration;

public sealed record DecisionTraceSnapshot(
    Guid Id,
    Guid? StrategySignalId,
    string CorrelationId,
    string DecisionId,
    string UserId,
    string Symbol,
    string Timeframe,
    string StrategyVersion,
    string SignalType,
    int? RiskScore,
    string DecisionOutcome,
    string? VetoReasonCode,
    int LatencyMs,
    string SnapshotJson,
    DateTime CreatedAtUtc,
    string? DecisionReasonType = null,
    string? DecisionReasonCode = null,
    string? DecisionSummary = null,
    DateTime? DecisionAtUtc = null,
    DateTime? LastCandleAtUtc = null,
    int? DataAgeMs = null,
    int? StaleThresholdMs = null,
    string? StaleReason = null,
    string? ContinuityState = null,
    int? ContinuityGapCount = null,
    DateTime? ContinuityGapStartedAtUtc = null,
    DateTime? ContinuityGapLastSeenAtUtc = null,
    DateTime? ContinuityRecoveredAtUtc = null);
