namespace CoinBot.Application.Abstractions.Administration;

public sealed record DecisionTraceWriteRequest(
    string UserId,
    string Symbol,
    string Timeframe,
    string StrategyVersion,
    string SignalType,
    string DecisionOutcome,
    string SnapshotJson,
    int LatencyMs,
    string? CorrelationId = null,
    string? DecisionId = null,
    int? RiskScore = null,
    string? VetoReasonCode = null,
    Guid? StrategySignalId = null,
    DateTime? CreatedAtUtc = null,
    string? DecisionReasonType = null,
    string? DecisionReasonCode = null,
    string? DecisionSummary = null,
    DateTime? DecisionAtUtc = null,
    DateTime? LastCandleAtUtc = null,
    int? DataAgeMs = null,
    int? StaleThresholdMs = null,
    string? StaleReason = null,
    string? ContinuityState = null,
    int? ContinuityGapCount = null,
    DateTime? ContinuityGapStartedAtUtc = null,
    DateTime? ContinuityGapLastSeenAtUtc = null,
    DateTime? ContinuityRecoveredAtUtc = null);
